name: ewu_map
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  logger: ^1.3.0
  path: ^1.8.2
  path_provider: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter_icons:
  image_path: "assets/icons/app-icon-1024x1024.png"
  android: true
  ios: true
  # command: flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash-icon-384x384.png"
  android: true
  ios: true
  web: true
  # command: flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/files/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/
    
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
